version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: nfc_db
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  nfcsecure:
    build: .
    container_name: nfcsecure-api
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nfc_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    command: ["java", "-jar", "/app.jar"]
